namespace WinUI3XamlPreview
{
[bindable]
unsealed runtimeclass ScaleValue : Windows.Foundation.IStringable
{
String DisplayName{get;};
Double Scale{get;};
String ToString();
}
}
namespace WinUI3XamlPreview
{
unsealed runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
{
MainPage();
static String ResolutionDisplay(Object resolutionFloat2);
static String ThemeDisplay(String theme);
static Windows.Foundation.Collections.IVector<Object> Resolutions();
static Windows.Foundation.Collections.IVector<Object> Scales();
}
}
